### ISSUE TITLE
os-agent_1.4.1_linux_amd64.tar.gz error: is not a Debian format archive

### ISSUE THREAD

**Issue by balogatt** [home-assistant/os-agent#112]
Hi!
I try to install on my new Linux but I got errors:
`wget https://github.com/home-assistant/os-agent/releases/tag/1.4.1/os-agent_1.4.1_linux_amd64.deb`
I get
`Mentés ide: ‘os-agent_1.4.1_linux_amd64.deb’
os-agent_1.4.1_linux_amd64.deb      [  <=>                                                       ] 114,39K   473KB/s    idő 0,2s   
2022-11-18 11:46:25 (473 KB/s) -- ‘os-agent_1.4.1_linux_amd64.deb’ mentve [117135]`
ok

Try:
` sudo dpkg -i os-agent_1.4.1_linux_amd64.deb`
`dpkg-deb: hiba: 'os-agent_1.4.1_linux_amd64.deb' is not a Debian format archive`

Same with os-agent_1.4.1_linux_amd64.tar.gz.

What is wrong?
-------
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by frenck** [comment]
> Description: Ubuntu 22.04.1 LTS

Ubuntu is not supported by the Home Assistant project. Please make sure to read the requirements.

../Frenck
