### ISSUE TITLE
arm64.deb is missing

### ISSUE THREAD

**Issue by garethhowell** [home-assistant/os-agent#127]
I'm trying to do. supervised install of HA on Debian 11 on a Pi 4, however there is no arm64.deb file. I tried installing from source, but the version of go-lan on Debian 11 is only 1.15 whereas this agent requires 1.18

**Comment by agners** [comment]
See #110.

For Debian on arm64, just use os-agent_1.4.1_linux_aarch64.deb.

**Comment by garethhowell** [comment]
Ta
