### ISSUE TITLE
Install on OrangePi 4 LTS

### ISSUE THREAD

**Issue by fabiorcosta** [home-assistant/os-agent#141]
I am not a linux expert, and trying to install HA on Opi 4 LTS using a guide I was told to use the following command:

curl -s [https://api.github.com/repos/home-assistant/os-agent/releases/latest 1](https://api.github.com/repos/home-assistant/os-agent/releases/latest) | grep “browser_download_url.*aarch64.deb” | cut -d : -f 2,3 | tr -d " | wget -O os-agent-aarch64.deb -i -

But it seems something is wrong since I am getting the error: no URLs found in -

Can someone help?

**Comment by frenck** [comment]
That command seems to be odd.

Please see/use our installation instructions here: <https://github.com/home-assistant/os-agent#installation--update>

../Frenck
