### ISSUE TITLE
Debian 11 (bullseye) os-agent package not recognized

### ISSUE THREAD

**Issue by leprechaun17** [home-assistant/os-agent#147]
trying to install latest os-agent package 1.5.1 and Debian 11 (bullseye) doesn't recognize it.

sudo dpkg -i os-agent_1.5.1_linux_x86_64.deb
dpkg-deb: error: 'os-agent_1.5.1_linux_x86_64.deb' is not a Debian format archive
dpkg: error processing archive os-agent_1.5.1_linux_x86_64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 os-agent_1.5.1_linux_x86_64.deb

I was able to install it with standard Debian 11 OS before but I decided to restart from scratch since I got a message from HASSIO telling I didn't have systemd installed.

**Comment by vhristev** [comment]
You need to install the `os-agent`

Check your Arch with `uname -a` then choose the correct one; https://github.com/home-assistant/os-agent/releases/tag/1.5.1 
https://github.com/home-assistant/os-agent/tree/main#using-home-assistant-supervised-on-debian


after that `apt install ./os-agent....'

Here is an example. As you can see I'm aarch64 ,so i download the linux_aarch64 os agent. 
```
root@rpi4-20230102:/home/vhristev# uname -a
Linux rpi4-20230102 5.10.0-20-arm64 #1 SMP Debian 5.10.158-2 (2022-12-13) aarch64 GNU/Linux
root@rpi4-20230102:/home/vhristev# ls -l os-agent_1.5.1_linux_aarch64.deb
-rw-r--r-- 1 root root 2614500 Mar 16 16:15 os-agent_1.5.1_linux_aarch64.deb
```

**Comment by wselph** [comment]
Same error:
root@wsdebian:~# uname -a
Linux wsdebian 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
root@wsdebian:~# sudo dpkg -i os-agent_1.5.1_linux_x86_64.deb
dpkg-deb: error: 'os-agent_1.5.1_linux_x86_64.deb' is not a Debian format archive
dpkg: error processing archive os-agent_1.5.1_linux_x86_64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 os-agent_1.5.1_linux_x86_64.deb
root@wsdebian:~#
 
Could there be an error within the source file?
Thank you

**Comment by agners** [comment]
The deb files in the release section should be fine.

GitHub releases use HTTP forwards, depending on the download method that might lead to an incorrectly downloaded file. Try redownload using a browser.
