### ISSUE TITLE
Odroid N2+ 

### ISSUE THREAD

**Issue by sponkpi** [home-assistant/os-agent#152]
Sorry, that i ask  here, but i use a Odroid N2+ for the first time an i don't know how to manage my problem. I want to install Home Assistant supervised an I tried the tutorial for that. But I only find a version for installing os-agent for arm64 which is a tar.gz file not a deb file. How can I install the tar.gz file? Can you please help me?

**Comment by agners** [comment]
See https://github.com/home-assistant/os-agent/issues/110.

For Debian on arm64, just use os-agent_1.4.1_linux_aarch64.deb.

Also: This is an issue tracker, not a community forum.
