### ISSUE TITLE
Install os-agent in Debian (inside docker container)

### ISSUE THREAD

**Issue by eduardorq** [home-assistant/os-agent#157]
I'm triying to install os-agent_1.5.1_linux_x86_64.deb in debian:stable image but show some errors:

`root@8f1d877355be:/# dpkg -i os-agent_1.5.1_linux_x86_64.deb 
(Reading database ... 15375 files and directories currently installed.)
Preparing to unpack os-agent_1.5.1_linux_x86_64.deb ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/docker.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/containerd.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/ModemManager.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/NetworkManager.service": No such device or address
Removed "/etc/systemd/system/multi-user.target.wants/haos-agent.service".
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/remote-fs.target": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/wpa_supplicant.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/e2scrub_reap.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sockets.target.wants/docker.socket": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.timesync1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/graphical.target.wants/udisks2.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-pstore.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-resolved.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/apparmor.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/getty.target.wants/getty@tty1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.resolve1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-fi.w1.wpa_supplicant1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/e2scrub_all.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/fstrim.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/apt-daily.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/dpkg-db-backup.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/docker.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/containerd.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/ModemManager.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/NetworkManager.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/remote-fs.target": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/wpa_supplicant.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/e2scrub_reap.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sockets.target.wants/docker.socket": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.timesync1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/graphical.target.wants/udisks2.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-pstore.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-resolved.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/apparmor.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/getty.target.wants/getty@tty1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.resolve1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-fi.w1.wpa_supplicant1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/e2scrub_all.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/fstrim.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/apt-daily.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/dpkg-db-backup.timer": No such device or address
dpkg: warning: old os-agent package pre-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/docker.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/containerd.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/ModemManager.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/NetworkManager.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/remote-fs.target": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/wpa_supplicant.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/multi-user.target.wants/e2scrub_reap.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.ModemManager1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sockets.target.wants/docker.socket": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.timesync1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/graphical.target.wants/udisks2.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-pstore.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-resolved.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/apparmor.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/getty.target.wants/getty@tty1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-org.freedesktop.resolve1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/dbus-fi.w1.wpa_supplicant1.service": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/e2scrub_all.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/fstrim.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/apt-daily.timer": No such device or address
Failed to disable unit, file "/etc/systemd/system/timers.target.wants/dpkg-db-backup.timer": No such device or address
dpkg: error processing archive os-agent_1.5.1_linux_x86_64.deb (--install):
 new os-agent package pre-removal script subprocess returned error exit status 1
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Created symlink /etc/systemd/system/multi-user.target.wants/haos-agent.service → /lib/systemd/system/haos-agent.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error while cleaning up:
 installed os-agent package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 os-agent_1.5.1_linux_x86_64.deb
`

And my hardware is x86_64... what's wrong?
`root@8f1d877355be:/# uname -a
Linux 8f1d877355be 4.4.180+ #42962 SMP Sat Apr 8 00:14:26 CST 2023 x86_64 GNU/Linux
`

Thanks.

**Comment by frenck** [comment]
>  what's wrong?

What is wrong, is that this is not meant to be installed in a container.
As you can see during startup it misses all kinds of software and device access.

Even if you made it work in a container, it would be pretty useless to run there.

Closing this issue, as this is not a use case this was designed for.

../Frenck
