### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mate60** [home-assistant/os-agent#160]
root@debian:/home/hzh# dpkg -i os-agent_1.5.1_linux_x86_64.deb
(Reading database ... 35214 files and directories currently installed.)
Preparing to unpack os-agent_1.5.1_linux_x86_64.deb ...
Unpacking os-agent (1.5.1) over (1.5.1) ...
dpkg: dependency problems prevent configuration of os-agent:
 os-agent depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package os-agent (--install):
 dependency problems - leaving unconfigured
Processing triggers for dbus (1.12.24-0+deb11u1) ...
Errors were encountered while processing:
 os-agent

**Comment by frenck** [comment]
The resolution to your issue is in the error message:

> os-agent depends on udisks2; however:
> Package udisks2 is not configured yet.

Please ensure to set up and configure that.

../Frenck
