### ISSUE TITLE
Please provide Ubuntu ARM64 deb package.

### ISSUE THREAD

**Issue by modosm** [home-assistant/os-agent#174]
I wanted to install the OS-agent on my RaspberryPi running Ubuntu but there is no deb package to do that.

Thank you.

**Comment by frenck** [comment]
There it is:

![CleanShot 2023-11-27 at 17 56 43@2x](https://github.com/home-assistant/os-agent/assets/195327/7a4fc8b8-d1d4-45b0-8419-dd523e22af7c)

<https://github.com/home-assistant/os-agent/releases/tag/1.6.0>

../Frenck
