### ISSUE TITLE
hassio_supervisor will not open port 8123 and broadcast the web page to it

### ISSUE THREAD

**Issue by BP023** [home-assistant/os-agent#177]
Hi all, im running this version of hassio on a Raspberry Pi 4B 4GB running Debian 12.
I've got it all installed and all of the containers are running, but i'm not too sure about why the container isn't broadcasting the web interface to port 8123. Tried looking for other solutions, but couldn't find them. Thank you

**Comment by agners** [comment]
The Supervisor doesn't run the web server on port 8123. The Supervisor runs in the background and manages the other containers. It is Home Assistant Core (the `homeassistant` container) which acts as web server. You might just need to wait a bit as the Supervisor might still download that container.
