### ISSUE TITLE
Release 1.6.0  is missing amd64.deb package

### ISSUE THREAD

**Issue by litinoveweedle** [home-assistant/os-agent#185]
Release [1.6.0](https://github.com/home-assistant/os-agent/releases/tag/1.6.0)  is missing builded amd64.deb package.

**Comment by frenck** [comment]
Just checked, but is there:

![image](https://github.com/home-assistant/os-agent/assets/195327/60188126-a825-499e-8681-2d3eae17f50c)

**Comment by litinoveweedle** [comment]
Hi thanks, I missed it, as it is not in Debian package nomenclature. For others x86_64/x86/amd64 is the same architecture, so x86_64 is used for os-agent, insted of Debian _amd64 default naming extension. Thanks for pointing this out.

**Comment by marbeja** [comment]
chatgpt also has not yet understood that the .deb don't exist but .tar
