### ISSUE TITLE
Add riscv64 release

### ISSUE THREAD

**Issue by eshattow** [home-assistant/os-agent#191]
Debian has accepted riscv64 and is no longer only in ports status. There is a functioning [debian-installer for riscv64](https://d-i.debian.org/daily-images/riscv64/) and it is running on real hardware (Home Assistant Yellow PoE with Milk-V Mars CM). The next step is software support for installing Home Assistant supervised. Can riscv64 arch be added for os-agent release? Thanks!

**Comment by frenck** [comment]
Hi there @eshattow 👋 

The Home Assistant project has strictly defined the architecture we support in an architectural decision record (stored in our architecture repository).

Therefore going to close this issue, as this is not an architecture we are currently willing to support.

../Frenck

**Comment by monsterLang** [comment]
Hi Frenck

Excuse me, is there any progress on the riscv64 version?

Thanks~

**Comment by eshattow** [comment]
@monsterLang I guess there will be no development at all until https://github.com/home-assistant/architecture/blob/master/adr/0013-home-assistant-container.md is ammended to include riscv64

**Comment by eshattow** [comment]
unfortunately upstream has locked discussion re: home-assistant/architecture#1107

discussion continues at Matrix chat and IRC named at https://github.com/haltrv/
