### ISSUE TITLE
gdbus: command not found

### ISSUE THREAD

**Issue by pavolholes** [home-assistant/os-agent#31]
Please add dependency on `libglib2.0-bin` because `gdbus` is not standard on Debian 10. I had to run
`sudo apt install libglib2.0-bin` to be able to run the command `gdbus introspect --system --dest io.hass.os --object-path /io/hass/os`

Solution provided by Jason Codes in the discussion:
https://community.home-assistant.io/t/supervisor-update/332629/20?u=palito

**Comment by pvizeli** [comment]
Right, According ADR for supervisors, people need able to deal with it or using the OS
