### ISSUE TITLE
No deb file for arm64 v1.2.0

### ISSUE THREAD

**Issue by ntsmkfob** [home-assistant/os-agent#38]
The installation instructions only cover using dpkg to install new versions.

**Comment by frenck** [comment]
That should be enough to use it. New deb files are provided each release and can be upgraded like any other Debian package.

**Comment by aventu90** [comment]
Sorry for reopening. I just want to leave a note for future readers:
"os-agent_1.2.1_linux_arm64.tar.gz" (or maybe another future version) only contains the binary file, but you also need a additional configs and service files, which you can find in .deb packages, eg. "os-agent_1.2.1_linux_x86_64.deb"

My manual setup looks like this:
\etc\dbus-1\system.d\io.hass.conf
\usr\lib\systemd\system\haos-agent.service
\usr\bin\os-agent

Enable the service with:
`systemctl enable \usr\lib\systemd\system\haos-agent.service`
`systemctl start haos-agent.service`

**Comment by suchalaugh** [comment]
I'm sorry, I dont get it and still don't know what to do. README is no help at all as it is for .deb at all.
What I did so far was:

wget https://github.com/home-assistant/os-agent/archive/refs/tags/1.2.2.tar.gz
tar -xzvf os-agent_1.2.2_linux_arm64.tar.gz
./os-agent 
and last one leads me to 
"INFO: 2021/11/10 19:51:15 main.go:31: Start OS-Agent 1.2.2
CRITICAL: 2021/11/10 19:51:15 main.go:55: Connection ":1.36" is not allowed to own the service "io.hass.os" due to security policies in the configuration file"

Thanks for help

**Comment by ntsmkfob** [comment]
The 64-bit Arm deb package os-agent_1.2.2_linux_aarch64.deb should work OK. Ignore the one you downloaded.

**Comment by blackbunt** [comment]
> \etc\dbus-1\system.d\io.hass.conf
> \usr\lib\systemd\system\haos-agent.service
> \usr\bin\os-agent

maybe this should be added to the README

**Comment by jafocol** [comment]
hi [blackbunt](https://github.com/blackbunt) I have tried to configure it manually but I have not been able to. I have this configuration that you say but when installing the supervisor it tells me:


`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 homeassistant-supervised : Depends: os-agent but it is not installable`

Does he know how I can check or monitor why he doesn't install it for me. thank you

**Comment by jafocol** [comment]
This is haos-agente service status: 


> ● haos-agent.service - Home Assistant OS Agent
     Loaded: loaded (/etc/systemd/system/haos-agent.service; enabled; preset: enabled)
     Active: active (running) since Fri 2023-11-10 00:25:46 UTC; 1 month 27 days ago
   Main PID: 1010 (os-agent)
      Tasks: 6 (limit: 4640)
     Memory: 14.2M
        CPU: 89ms
     CGroup: /system.slice/haos-agent.service
             └─1010 /usr/bin/os-agent

Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 main.go:67: Listening on service io.hass.os ...
Nov 10 00:25:46 server os-agent[1010]: WARNING: 2023/11/10 00:25:46 datadisk.go:106: Can't find a data mount!
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 datadisk.go:154: Exposing object /io/hass/os/DataDisk with interface io.hass.os.DataDisk ...
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 system.go:161: Exposing object /io/hass/os/System with interface io.hass.os.System ...
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 apparmor.go:116: Exposing object /io/hass/os/AppArmor with interface io.hass.os.AppArmor ...
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 cgroup.go:115: Detected CGroups Version 2
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 cgroup.go:143: Exposing object /io/hass/os/CGroup with interface io.hass.os.CGroup ...
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 boards.go:69: Exposing object /io/hass/os/Boards with interface io.hass.os.Boards ...
Nov 10 00:25:46 server os-agent[1010]: INFO: 2023/11/10 00:25:46 supervised.go:47: Exposing object /io/hass/os/Boards/Supervised with interface io.hass.os.Boards.Supervised ...
Nov 10 00:25:46 server systemd[1]: Started haos-agent.service - Home Assistant OS Agent.
