### ISSUE TITLE
Udisks2 should be added as a dependency 

### ISSUE THREAD

**Issue by Trev-W** [home-assistant/os-agent#39]
When installing os-agent_1.2.1_linux_x86_64.deb dpkg complains about udisks2 missing, installing and then fix-broken install fixes the issue retrospectively

**Comment by frenck** [comment]
It is already a dependency:

https://github.com/home-assistant/os-agent/blob/main/.goreleaser.yml#L40-L41

That is why it complained about it in the first place 😬
