### ISSUE TITLE
package architecture (amd64) does not match system (armhf)

### ISSUE THREAD

**Issue by francisp2** [home-assistant/os-agent#46]
dpkg: error processing archive os-agent_1.2.2_linux_armv7.deb (--install):
 package architecture (amd64) does not match system (armhf)

**Comment by nardev** [comment]
Any updated on this one? Having the same issue here.

**Comment by inferusvv** [comment]
@francisp2 How did you resolved it? I am trying to install os-agent on Raspberry Pi OS Lite (4/4gb)

**Comment by qfaure** [comment]
same issue

**Comment by frenck** [comment]
> Raspberry Pi OS Lite

Is not supported. Please be sure to read the requirement of the Home Assistant Supervised installation type.

Thanks 🙏

**Comment by inferusvv** [comment]
@frenck It is supported. Just take armv7 bundle :)

**Comment by qfaure** [comment]
@inferusvv  i testing it this morning, but not working :/
<img width="874" alt="Screenshot 2022-01-05 at 15 42 02" src="https://user-images.githubusercontent.com/36954980/148236180-c6ff57b7-48bb-45be-9eb3-60679c61de80.png">

**Comment by inferusvv** [comment]
@qfaure Are you using Debian? I am using Raspberry Pi OS Lite and everything installed fine.

**Comment by qfaure** [comment]
Using this one :

<img width="380" alt="Screenshot 2022-01-05 at 15 44 57" src="https://user-images.githubusercontent.com/36954980/148236664-2a2374e5-c226-41d7-a2c5-03eaa721a601.png">

**Comment by frenck** [comment]
> @frenck It is supported

So let me be clear. Raspberry Pi OS **is not** supported.
Please check the requirements for this installation method here:

<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions>

![image](https://user-images.githubusercontent.com/195327/148237166-a4d19539-695c-46b4-940e-1cc4b3e940b2.png)

Raspberry Pi OS is a derivative.

Please move the conversation and issue with using a non-supported system out of our issue tracker (as they are unsupported by the Home Assistant project).

Thanks 👍
