### ISSUE TITLE
Missing gdbus on debian install

### ISSUE THREAD

**Issue by giffordj** [home-assistant/os-agent#51]
I'm using a Debian 11 minimal install for my home assistant.

You need to install glib-2.0 in order to have gdbus.

Recommend adding to notes, if missing gdbus, do the following apt-get install libglib2.0-bin .

**Comment by supersonical** [comment]
> I'm using a Debian 11 minimal install for my home assistant.
> 
> You need to install glib-2.0 in order to have gdbus.
> 
> Recommend adding to notes, if missing gdbus, do the following apt-get install libglib2.0-bin .

Thank you! saved me alot of time troubleshooting!

**Comment by agners** [comment]
Note added to the readme.
