### ISSUE TITLE
how to install non .deb files?

### ISSUE THREAD

**Issue by schluden** [home-assistant/os-agent#52]
On my Raspberry Pi, running Debian 11 (bullseye) I had to download the `os-agent_1.2.2_linux_arm64.tar.gz`
Simply extracting does not do the job. The supervised-installer complains about missing os-agent

`dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on os-agent; however:
  Package os-agent is not installed.`

So how do we handle the tar.gz file for arm64? Maybe you can add this information to the readme

**Comment by nadnerb33** [comment]
Incase anyone else has similar issues...
I installed `os-agent_1.2.2_linux_aarch64.deb` on my Raspberry Pi 4 (Debian 10 buster) and kept getting dependency errors when installing `homeassistant-supervised.deb`.
I then installed `os-agent_1.2.2_linux_armv7.deb` and now it works.

**Comment by Quantriple** [comment]
> The 64-bit Arm deb package `os-agent_1.2.2_linux_aarch64.deb` should do it.

Thank you very much. It's been bothering me for a week,
