### ISSUE TITLE
OS-Agent Notification

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/os-agent#56]
Since OS-Agent is required to run under Debian / Supervisor, shouldn't there be some type of notification built-in to show that there is an update to OS-Agent?

**Comment by ludeeus** [comment]
This is not something the os-agent can or should do.
Use the [GitHub integration](https://www.home-assistant.io/integrations/github)

**Comment by bschatzow** [comment]
I do have the GitHub integration. The sensor only shows latest version. No way to do a comparison of what is installed.

**Comment by bschatzow** [comment]
@ludeeus I am not understanding your comment. Os-agent is not a requirement of Debian.  It is a requirement of Home Assistant.  Why wouldn't it be a good idea for Home Assistant to have sensors showing the status of the required agent? It does this for the supervisor.

**Comment by ludeeus** [comment]
OS Agent is host software, it cannot and should not create _anything_ inside Home Assistant.
