### ISSUE TITLE
Question: Getting latest with wget

### ISSUE THREAD

**Issue by Hamsterman** [home-assistant/os-agent#60]
I am doing this
wget https://github.com/home-assistant/os-agent/releases/latest/download/os-agent_1.2.2_linux_x86_64.deb

But how can I convert my wget into a "get latest" instead

Thanks

**Comment by agners** [comment]
We are using regular GitHub releases.

Maybe something like this helps?
https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo

**Comment by Hamsterman** [comment]
The problem is that I can't figure out what the "package" name for it to work.

https://github.com/USER/PROJECT/releases/latest/download/package.zip

You have put the version in the actual file name.

If you look here:
https://github.com/home-assistant/supervised-installer/releases
There is no version in the file name so you can use this:
wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb

**Comment by iFFgen** [comment]
curl -s https://api.github.com/repos/home-assistant/os-agent/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep x86_64 | wget -i - -O os-agent_linux_x86_64.deb
