### ISSUE TITLE
CRITICAL: 2021/12/10 21:27:44 main.go:55: Connection ":1.1920" is not allowed to own the service "io.hass.os" due to security policies in the configuration file

### ISSUE THREAD

**Issue by userosos** [home-assistant/os-agent#61]
user@nuc:~$ os-agent --vesrion
INFO: 2021/12/10 21:27:44 main.go:31: Start OS-Agent 1.2.2
CRITICAL: 2021/12/10 21:27:44 main.go:55: Connection ":1.1920" is not allowed to own the service "io.hass.os" due to security policies in the configuration file
The error can be connected with the error https://github.com/home-assistant/architecture/issues/681

**Comment by agners** [comment]
Closing in favor of #64 which contains more information
