### ISSUE TITLE
unhealthy installation if OS-agent is installed

### ISSUE THREAD

**Issue by cociweb** [home-assistant/os-agent#63]
Hello,

Since the Home Assitant Supervised deb installer requires the OS-Agent, I've installed it with the latest version.
After a re-installation (and reloaded a previous backup) the installation became unhealthy and the Supervisor stack at the setup phase, and I got a tons of python errors recursivelly, and then it stucks:

https://pastebin.com/ii72f9vt

When I finish the installation of home assistant, and remove the OS-agent everything is working like a charm. 

I know, I have an unsupported OS, but since the OS-agent is a requirement for the hass dpkg installer, I thought I report it here.

**Comment by cociweb** [comment]
hmm let me add, if I remove the os-agent (with `sudo dpkg -r --force-depends os-agent`) the HASS working well, but it destroys my apt update mechanism: it would like to remove the homeassistant-supervised package, since the os-agent dependency is not fulfilled. until it is not removed the it is impossible to do an `apt upgrade`... (marking with hold flag for the hass, will not solve the problem)

**Comment by frenck** [comment]
> I know, I have an unsupported OS

Please try the supported methods (which include the operating system requirements).
Feel free to reopen when the issue still occurs at that moment.
