### ISSUE TITLE
no debian package file for AMD64

### ISSUE THREAD

**Issue by GoState** [home-assistant/os-agent#67]
This may be a newbie thing but I'm running on and AMD processor and when I try to install the os-agent for amd64 its only available in the .tar.gz and if I extract it it still doesn't work (following the directions on the os-agent page).

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/150095349-51d396ed-e899-44de-8fe9-00ecf56dd32d.png)

It is right there?
