### ISSUE TITLE
[ARMv6] Installation problem 

### ISSUE THREAD

**Issue by fvzptr** [home-assistant/os-agent#68]
I am trying to install os-agent on raspbarry pi 1 model b which has armv6 architecture.
I use the version for armv7 and I get the following error:
![err_installation](https://user-images.githubusercontent.com/43762626/150647764-61dcdf3a-6650-438f-9ac6-0f3e5e26975f.jpg)

Looking at the log the error is as follows:
![log_installation](https://user-images.githubusercontent.com/43762626/150647821-1a0a11fd-3721-48f8-8d69-613b34d386ee.jpg)

The error is a result of trying to use your ARMv7 binary on ARMv6. All the quad-core Pi’s (2, 3 and 3+) are v7 while the single-core (A, B, and Zero) are v6. Installation works fine since Raspbian is “armhf”, however the binary will get a SIGKILL due to illegal instructions.

Could you please make the binary ARMv6 compatible to allow use on all Raspberry Pi’s?

**Comment by agners** [comment]
IMHO, if anything, there should be an additional binary for ARMv6(K) variant instead of making the ARMv7 variant ARMv6 compatible. Did you try `os-agent_1.2.2_linux_armv5.deb`?

**Comment by fvzptr** [comment]
Yes I tried before opening the ticket but it doesn't install and the error message is "not compatible with ARMv6 architecture".
I agree with you. Can I already do something? I state that I am not very expert. Or do I have to wait for binary armV6 (K) to be added?

**Comment by bartplessers** [comment]
ah, same as #69 

@agners 
>All that said, I'd recommend to move to a newer Hardware in any case.
True, but I'm just so proud that I'm running HA on ALL my RPI's (1,2,3 and 4). :-)

So it's not for production, but in rare cases, I can use it for development...
No possibility to get a working version of os-agent on a RPI1?

grtz
B

**Comment by mik13ST** [comment]
I am in the same situation: trying to install os-agent on a RPi1 (the root of the problem is the HA for rpi3 or rpi4 didn't boot so I am doing a supervised install).

It seems like I got around the issue by simply building this package from source (you have to install Go first), then installing the armv7 version and then replacing the `/usr/bin/os-agent` with my built os-agent binary. It takes about 10 minutes to build on RPi1. It's not clean, but seems to work.

**Comment by domerich** [comment]
I have the same problem, can someone please provide help for Pi Zero W armv6
is there any nightly package available?

**Comment by mik13ST** [comment]
Here is my build that I am using on my RPi1 which also is armv6. Don't remember which commit or version it is though.

[os-agent.zip](https://github.com/home-assistant/os-agent/files/9139908/os-agent.zip)

**Comment by domerich** [comment]
> Here is my build that I am using on my RPi1 which also is armv6. Don't remember which commit or version it is though.
> 
> [os-agent.zip](https://github.com/home-assistant/os-agent/files/9139908/os-agent.zip)

thanks a lot. can I install this with the dpkg -i command? I am just an iOS / windows user with low debian skills ...

**Comment by mik13ST** [comment]
What your friend suggested (wget, uzip, cp) is correct.

**Comment by mik13ST** [comment]
Also, just to be sure, run `chmod +x /usr/bin/os-agent` to turn on the flag that allows the binary to be executed.

**Comment by domerich** [comment]
> Also, just to be sure, run `chmod +x /usr/bin/os-agent` to turn on the flag that allows the binary to be executed.

Do I have to do anything after that? I still get a lot of errors. I am now running 

`apt --fix-broken install`


```
Adding 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Adding 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Adding 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Adding 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.2.1) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on network-manager; however:
  Package network-manager is not installed.
 homeassistant-supervised depends on apparmor; however:
  Package apparmor is not installed.
 homeassistant-supervised depends on jq; however:
  Package jq is not installed.
 homeassistant-supervised depends on os-agent; however:
  Package os-agent is not configured yet.
```

**Comment by mik13ST** [comment]
I am going to summarize what I did to get os-agent working on arm6 RPi1:

1. install [os-agent_1.2.2_linux_armv7.deb](https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_armv7.deb) from the releases page
2. you will get `installed os-agent package post-installation script subprocess returned error exit status 1`, continue
3. now download and unzip my build (version 1.2.2) from https://github.com/home-assistant/os-agent/files/9139908/os-agent.zip
4. move (replace) my build to /usr/bin/os-agent
5. run `os-agent`, you should get some output

```
wget https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_armv7.deb
dpkg -i os-agent_1.2.2_linux_armv7.deb
wget https://github.com/home-assistant/os-agent/files/9139908/os-agent.zip
unzip os-agent.zip
mv os-agent /usr/bin/os-agent
chmod +x /usr/bin/os-agent

os-agent
```

Keep in mind you are trusting me with the contents of the binary. You can always just compile it yourself on the device.

I should correct myself, I didn't succeed with the supervised install. I hoped it wouldn't use Docker, but it does. Using Docker on a low power hardware like RPi1 seems like a waste of resources. Also, I was limited in storage size to a 4GB SD card and Docker images easily consumed what was left after raspbian lite. I instead went with the manual install (setting up Python env etc.).

**Comment by mik13ST** [comment]
> I still get a lot of errors. I am now running `apt --fix-broken install`

As for your problems, I recommend starting from scratch with a clean raspbian lite image. I recommend installing os-agent well ahead of hass. Because the post-installation script of os-agent fails, the hass supervised install fails and leaves the system in an odd state, it seems.

**Comment by domerich** [comment]
> > I still get a lot of errors. I am now running `apt --fix-broken install`
> 
> As for your problems, I recommend starting from scratch with a clean raspbian lite image. I recommend installing os-agent well ahead of hass. Because the post-installation script of os-agent fails, the hass supervised install fails and leaves the system in an odd state, it seems.

ok thanks for the help but I quit. Need to buy a berry 4 at some point.
Everytime I try it kills my wifi and ssh connection and there is no way to enable it on a Pi Zero W with just a wifi connecition.
I do not recommend to try this unless you are a pro

**Comment by dudusandi** [comment]
> I am going to summarize what I did to get os-agent working on arm6 RPi1:
> 
>     1. install [os-agent_1.2.2_linux_armv7.deb](https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_armv7.deb) from the releases page
> 
>     2. you will get `installed os-agent package post-installation script subprocess returned error exit status 1`, continue
> 
>     3. now download and unzip my build (version 1.2.2) from https://github.com/home-assistant/os-agent/files/9139908/os-agent.zip
> 
>     4. move (replace) my build to /usr/bin/os-agent
> 
>     5. run `os-agent`, you should get some output
> 
> 
> ```
> wget https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_armv7.deb
> dpkg -i os-agent_1.2.2_linux_armv7.deb
> wget https://github.com/home-assistant/os-agent/files/9139908/os-agent.zip
> unzip os-agent.zip
> mv os-agent /usr/bin/os-agent
> chmod +x /usr/bin/os-agent
> 
> os-agent
> ```
> 
> Keep in mind you are trusting me with the contents of the binary. You can always just compile it yourself on the device.
> 
> I should correct myself, I didn't succeed with the supervised install. I hoped it wouldn't use Docker, but it does. Using Docker on a low power hardware like RPi1 seems like a waste of resources. Also, I was limited in storage size to a 4GB SD card and Docker images easily consumed what was left after raspbian lite. I instead went with the manual install (setting up Python env etc.).


Clean install after this \/

pi@hassio:/mnt/hassio $ sudo os-agent
INFO: 2023/01/16 23:00:02 main.go:31: Start OS-Agent mkbuild1.2.2
CRITICAL: 2023/01/16 23:00:02 main.go:58: name already taken

**Comment by mik13ST** [comment]
@dudusandi That has something to do with DBus? See the code at https://github.com/home-assistant/os-agent/blob/1.2.2/main.go#L58. I have no idea. Never had this problem.

I recently reinstalled HASS on my RPi1 manually (always used manual) and found out you don't need os-agent anymore. Maybe it was needed by mistake? I don't know. My version is "Home Assistant Core 2022.6.7".

Here is the proof:
```
pi@rpi1:~ $ os-agent
-bash: os-agent: command not found
pi@rpi1:~ $ systemctl status hass.service
● hass.service - Home Assistant
     Loaded: loaded (/etc/systemd/system/hass.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-01-16 20:49:26 CET; 3h 28min ago
   Main PID: 438 (hass)
      Tasks: 12 (limit: 415)
        CPU: 33min 33.628s
     CGroup: /system.slice/hass.service
             └─438 /srv/homeassistant/bin/python3 /srv/homeassistant/bin/hass -c /home/pi/.homeassistant

Jan 16 23:54:56 rpi1 hass[438]: 2023-01-16 23:54:56 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 16 23:54:56 rpi1 hass[438]: 2023-01-16 23:54:56 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:00:09 rpi1 hass[438]: 2023-01-17 00:00:09 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:00:10 rpi1 hass[438]: 2023-01-17 00:00:10 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:05:22 rpi1 hass[438]: 2023-01-17 00:05:22 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:05:23 rpi1 hass[438]: 2023-01-17 00:05:23 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:10:35 rpi1 hass[438]: 2023-01-17 00:10:35 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:10:36 rpi1 hass[438]: 2023-01-17 00:10:36 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:15:48 rpi1 hass[438]: 2023-01-17 00:15:48 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
Jan 17 00:15:49 rpi1 hass[438]: 2023-01-17 00:15:49 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
pi@rpi1:~ $
```

**Comment by dudusandi** [comment]
> @dudusandi That has something to do with DBus? See the code at https://github.com/home-assistant/os-agent/blob/1.2.2/main.go#L58. I have no idea. Never had this problem.
> 
> I recently reinstalled HASS on my RPi1 manually (always used manual) and found out you don't need os-agent anymore. Maybe it was needed by mistake? I don't know. My version is "Home Assistant Core 2022.6.7".
> 
> Here is the proof:
> 
> ```
> pi@rpi1:~ $ os-agent
> -bash: os-agent: command not found
> pi@rpi1:~ $ systemctl status hass.service
> ● hass.service - Home Assistant
>      Loaded: loaded (/etc/systemd/system/hass.service; enabled; vendor preset: enabled)
>      Active: active (running) since Mon 2023-01-16 20:49:26 CET; 3h 28min ago
>    Main PID: 438 (hass)
>       Tasks: 12 (limit: 415)
>         CPU: 33min 33.628s
>      CGroup: /system.slice/hass.service
>              └─438 /srv/homeassistant/bin/python3 /srv/homeassistant/bin/hass -c /home/pi/.homeassistant
> 
> Jan 16 23:54:56 rpi1 hass[438]: 2023-01-16 23:54:56 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 16 23:54:56 rpi1 hass[438]: 2023-01-16 23:54:56 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:00:09 rpi1 hass[438]: 2023-01-17 00:00:09 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:00:10 rpi1 hass[438]: 2023-01-17 00:00:10 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:05:22 rpi1 hass[438]: 2023-01-17 00:05:22 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:05:23 rpi1 hass[438]: 2023-01-17 00:05:23 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:10:35 rpi1 hass[438]: 2023-01-17 00:10:35 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:10:36 rpi1 hass[438]: 2023-01-17 00:10:36 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:15:48 rpi1 hass[438]: 2023-01-17 00:15:48 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> Jan 17 00:15:49 rpi1 hass[438]: 2023-01-17 00:15:49 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect >
> pi@rpi1:~ $
> ```

how did you install?

**Comment by frenck** [comment]
He didn't. The feature for armv6 has been merged, but not released yet.
It will be part of the next release of the os-agent.

../Frenck

**Comment by dudusandi** [comment]
> 

:(

**Comment by mik13ST** [comment]
My manual install of HASS was done according to these: https://www.home-assistant.io/installation/linux#install-home-assistant-core. I did the `apt install` of many things, set up Python virtual environment and stuff. I wanted hass as a systemd service so it runs on startup and the definition of such a service is not provided anywhere so I made my own.

```
pi@rpi1:~ $ cat /etc/systemd/system/hass.service
[Unit]
Description=Home Assistant
After=network-online.target

[Service]
Type=simple
WorkingDirectory=/home/pi/.homeassistant
ExecStart=/srv/homeassistant/bin/hass -c "/home/pi/.homeassistant"
RestartForceExitStatus=100

[Install]
WantedBy=multi-user.target
pi@rpi1:~ $
```

You have to run `systemctl daemon-reload` for systemd to rescan for new service definitions. Then you can `start` and `enable` the service (assuming you want to run hass on startup).

This is no longer related to os-agent.

**Comment by frenck** [comment]
Marked your comment as off-topic @mik13ST, it is not related to this issue.

**Comment by dudusandi** [comment]
> My manual install of HASS was done according to these: https://www.home-assistant.io/installation/linux#install-home-assistant-core. I did the `apt install` of many things, set up Python virtual environment and stuff. I wanted hass as a systemd service so it runs on startup and the definition of such a service is not provided anywhere so I made my own.
> 
> ```
> pi@rpi1:~ $ cat /etc/systemd/system/hass.service
> [Unit]
> Description=Home Assistant
> After=network-online.target
> 
> [Service]
> Type=simple
> WorkingDirectory=/home/pi/.homeassistant
> ExecStart=/srv/homeassistant/bin/hass -c "/home/pi/.homeassistant"
> RestartForceExitStatus=100
> 
> [Install]
> WantedBy=multi-user.target
> pi@rpi1:~ $
> ```
> 
> You have to run `systemctl daemon-reload` for systemd to rescan for new service definitions. Then you can `start` and `enable` the service (assuming you want to run hass on startup).
> 
> This is no longer related to os-agent.

I tried this but the setup takes more than 10 hours on RPI ZERO W, and this is Core install not Supervisor

**Comment by frenck** [comment]
Locking the issue. If you want to discuss general/other things, please use our community forums or Discord chat. Thanks 👍 

../Frenck
