### ISSUE TITLE
deb missing for ARM64

### ISSUE THREAD

**Issue by SunsetGolfer** [home-assistant/os-agent#71]
As there is only the executable for ARM64 I need instruction how to install this..

Pi4
diet-pi 8.1

Thanks

**Comment by agners** [comment]
Manual installation is only required with Supervised. With Supervised Debian 11 is only supported. You can find how-to on the community website: [Installing Home Assistant Supervised on a Raspberry Pi with Debian 11](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-11/247116)
