### ISSUE TITLE
error: 'os-agent_1.2.2_linux_armv7.deb' is not a Debian format archive on Raspberry Pi 4B

### ISSUE THREAD

**Issue by SPYR0999** [home-assistant/os-agent#86]
When trying to install the os-agent using dpkg, the error "error: 'os-agent_1.2.2_linux_armv7.deb' is not a Debian format archive" appears.

Here is the process I am using to download and install the package:
`sudo wget https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_armv7.deb`
`sudo dpkg -i os-agent_1.2.2_linux_armv7.deb`

I am using a Raspberry pi 4 running the latest version of Debian.

**Comment by agners** [comment]
Are you using 32-bit version of Debian?

This is likely due to a download error or similar, can you check the checksum?

**Comment by SPYR0999** [comment]
I am on the 64-bit version of debian. I managed to use the aarch64 package. I think my issue was related to trying a 32-bit package on a 64-bit system.
