### ISSUE TITLE
Trying to install on Mac OS using UTM and Debian. Cannot find the amd64.deb file. Only the tar file

### ISSUE THREAD

**Issue by asinla** [home-assistant/os-agent#94]
Hi.

In the os agent releases all the amd64 files are .tar.gz files. I have tried different things to get to the .deb file but nothing is working.
As it stands I cannot install the correct version for my Debian on an Intel Mac.

Thanks for any advice.

**Comment by pasqualepalmaccio** [comment]
Quote!! I can't install os-agent for arm64

**Comment by agners** [comment]
For Intel based Mac, which presumably runs a x86-64 based Debian, `os-agent_1.3.0_linux_x86_64.deb` should work.

For 64-Bit ARM there is also `os-agent_1.3.0_linux_aarch64.deb`.

**Comment by frenck** [comment]
Closing issue as per answer above.

../Frenck
